# Generated by Django 3.2.20 on 2023-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bio',
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_wedding',
            field=models.DateField(default='Unknown'),
        ),
    ]
