# Generated by Django 3.2.20 on 2023-07-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20230716_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_wedding',
            field=models.DateField(default='2024-12-31'),
        ),
    ]
