# Generated by Django 3.2.20 on 2023-07-16 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_date_of_wedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_of_wedding',
        ),
        migrations.AddField(
            model_name='customer',
            name='wedding_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
