# Generated by Django 3.2.20 on 2023-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20230716_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wedding_date',
            field=models.CharField(max_length=10),
        ),
    ]
