# Generated by Django 3.2.20 on 2023-07-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20230720_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
