# Generated by Django 3.2.20 on 2023-08-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20230819_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=30),
        ),
        migrations.AlterField(
            model_name='availableday',
            name='friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='availableday',
            name='monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='availableday',
            name='saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='availableday',
            name='tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='availableday',
            name='wednesday',
            field=models.BooleanField(default=True),
        ),
    ]
