# Generated by Django 3.2.20 on 2023-08-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_availabletime_store_not_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Enter the time you wish your calendar to close for bookings'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='start_time',
            field=models.TimeField(help_text='Enter the time you wish your calendar to open for bookings', null=True),
        ),
    ]
