# Generated by Django 3.2.20 on 2023-08-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20230819_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletime',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Enter the time you wish your calendar to close for bookings', null=True),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Enter the time you wish your calendar to open for bookings', null=True),
        ),
    ]
