# Generated by Django 3.2.20 on 2023-08-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20230820_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabledate',
            name='test_text',
            field=models.CharField(default='This is from the model', max_length=100),
        ),
    ]
