# Generated by Django 3.2.20 on 2023-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colours',
            field=models.TextField(blank=True, default='Ivory', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes_avail',
            field=models.TextField(blank=True, default='Enquire in store', max_length=500),
        ),
    ]
