# Generated by Django 3.2.20 on 2023-07-30 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_alter_product_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favourites',
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(related_name='single_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
